### ISSUE TITLE
netx: make netx.CertPool private

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#1018]
Noticed it being public may be confusing during https://github.com/ooni/probe-engine/pull/978 review.

**Comment by cyBerta** [comment]
Currently it seems to be the only way to set different CA certs. If the CertPool becomes private, it would be cool to be able to assign either certs (e.g. array of pem string formatted entries) or a configured certpool to a urlGetter.Config.

**Comment by bassosimone** [comment]
> If the CertPool becomes private, it would be cool to be able to assign either certs (e.g. array of pem string formatted entries) or a configured certpool to a urlGetter.Config.

Yes, we need to implement this to allow for your use case (see https://github.com/ooni/probe-engine/issues/1019). Will look into it on Monday! Thank you!

**Comment by bassosimone** [comment]
Done in https://github.com/ooni/probe-engine/pull/1020
