### ISSUE TITLE
cli,desktop,mobile: riseupvpn is part of the circumvention group

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#1060]
This issues describes the work required to make sure the RiseupVPN experiment is added to the circumvention group of experiments. We need to add it to the cli, to mobile apps, and to desktop apps.

**Comment by bassosimone** [comment]
Postponing to next Sprint.

**Comment by bassosimone** [comment]
We started working on this topic but we have not made significant progress yet, so moving to next Sprint.

**Comment by bassosimone** [comment]
Status update at the end of Sprint 30:

- ooni/probe-engine ✔️
- ooni/probe-cli ✔️
- ooni/probe-android ✔️
- ooni/probe-ios ⏳
- ooni/probe-desktop ⏳

Cc: @agrabeli, @sarathms, @lorenzoPrimi, @cyBerta

**Comment by bassosimone** [comment]
We will continue working on this issue in the next Sprint.

**Comment by bassosimone** [comment]
We've merged support for RiseupVPN in probe-desktop here: https://github.com/ooni/probe-desktop/pull/193.

We also merged iOS support here: https://github.com/ooni/probe-ios/pull/418.

So, we're done!!! :-)

**Comment by cyBerta** [comment]
That is sooo cool. We're really happy to see all of your engagement. I would like to invest some time in march for the DPI detection work on top of what has been reached so far. That might be interesting for more sophisticated tor tests as well.
