### ISSUE TITLE
Start triaging data quality issues

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#1062]
We have a bunch of issues related to measurement/data quality. I've applied the "triage" label to many of them but there are much more. I think the time is now ripe to reorganise all these issues and prepare for addressing them.

**Comment by bassosimone** [comment]
Postponing to next Sprint.

**Comment by bassosimone** [comment]
I have started doing this task now. I will continue and finish in the next Sprint.

**Comment by hellais** [comment]
This is wishful thinking, we should be doing this periodically anyways and we don't think it needs a dedicated issue. Closing.
