### ISSUE TITLE
Use mobile user-agents as well

### ISSUE THREAD

**Issue by darkk** [ooni/probe-engine#108]
`net.userAgents` has nothing but ancient Firefox.

We should have greater diversity of the User-Agents as we've seen mobile-targeted injections.

**TBD**: find some source of up-to-date UA statistics.

**Comment by anadahz** [comment]
Adding Smart TV UAs may bring some interesting measurements.

> TBD: find some source of up-to-date UA statistics.

https://developers.whatismybrowser.com/useragents/explore/

**Comment by bassosimone** [comment]
See #147 as well.

**Comment by bassosimone** [comment]
Consolidated info from this issue in #147. Closing as duplicate to reduce issue fatigue.
