### ISSUE TITLE
Detect QUIC blocking

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/probe-engine#121]
QUIC is becoming a popular protocol at it might be blocking, throttled or otherwise mangled by some devices because it uses UDP.

**Comment by bassosimone** [comment]
There are two possible approaches here:

1. measure the blocking (or throttling) of QUIC with a performance test

2. upgrade to http3 and see if we can fetch resources

Both are very interesting. We have also a technique about this: https://github.com/ooni/spec/blob/master/techniques/tq-035-block-quic.md

**Comment by bassosimone** [comment]
Since ~today we have support for http3 in `master`. We are also starting to run some testing `http3` measurements.

**Comment by bassosimone** [comment]
Work has been done in https://github.com/ooni/probe-engine/issues/747
