### ISSUE TITLE
Detect Signal Private Messenger blocking

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/probe-engine#124]
https://signal.org/ is designed for privacy. Albeit low on popularity, it could be a prime target for blocking.

**Comment by hellais** [comment]
This is duplicate of: https://github.com/ooni/spec/issues/149

**Comment by hellais** [comment]
I guess we should move the ooni/spec issue in here.

**Comment by agrabeli** [comment]
A Signal test has been requested by several community members multiple times over the last years.

**Comment by bassosimone** [comment]
Yes, this is a duplicate and I will close this issue. We should see to avoid having too many repositories where issues could be opened, because dealing with dupes is not pleasant.
