### ISSUE TITLE
Consider updating the UA of Web Connectivity test

### ISSUE THREAD

**Issue by anadahz** [ooni/probe-engine#137]
The User-Agent of Web Connectivity test is: `Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36` According to its [spec](https://github.com/ooni/spec/blob/fcabb0a9b42a83c3360401fda9bd4bb44cc51cdb/nettests/ts-017-web-connectivity.md#test-description) this UA corresponds to the most popular version (47.0.2526.106) of the most popular browser (Chrome) on the most popular OS (Windows 7).

This is most probably not anymore the case as this UA set is now 5 years old.

@bassosimone re: https://github.com/ooni/probe-engine/blob/ecb93b48ec58a466b216c97bef3df2cf41e362ce/experiment/useragent/useragent.go#L6-L8
Not sure if this is a related issue.

**Comment by bassosimone** [comment]
Thank you! I've consolidated your concerns in #147. Closing so we don't have too many issues!
