### ISSUE TITLE
Signal messenger experiment

### ISSUE THREAD

**Issue by hellais** [ooni/probe-engine#244]
Moving this issue from: https://github.com/measurement-kit/measurement-kit/issues/1396

It would be great to also be testing for reachability of the signal app, even better if we could do it via the actual Signal protocol.

Having some input from the developers of Signal on how it would be best to implement a Signal test would make this task much easier.

Some of the things we would need to do this include:

* [ ] Knowing what are the endpoints the Signal app connects to when performing all of it's operations (ex. registering a new number, receiving a message, receiving a call, etc.)
* [ ] Knowing how to check for consistency between endpoint hostname and IP
* [ ] Knowing what we need to do to "speak" a minimal amount of the Signal protocol to ensure everything works fine. If that is going to be painful to maintain in the longrun, because the protocol may change in the future, then we should just do basic reachability (i.e. do a TCP connect to endpoint:port)
* [ ] Knowing if there is any useful other data that we should be collecting that would make the Signal developers happy to learn about from our various vantage points

@moxie0 @liliakai do you think you folks could help us in going through this checklist?
What would be even cooler is if there were some C++ library we could link to in order to at best test the signal protocol.

**Comment by Te-k** [comment]
Updating that quickly, it seems that [signal](https://github.com/signalapp/Signal-Android/blob/master/app/build.gradle) is now using the following domains :  https://textsecure-service.whispersystems.org/ https://storage.signal.org/ https://cdn.signal.org/ https://uptime.signal.org/  https://api.directory.signal.org/  https://api.backup.signal.org/ https://contentproxy.signal.org/ 

https://cdn.signal.org/ and https://uptime.signal.org/ are listed in the config file but don't seem to be working, so you can test the working domains with  https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Ftextsecure-service.whispersystems.org%2F%22%2C%22https%3A%2F%2Fstorage.signal.org%2F%22%2C%22https%3A%2F%2Fapi.directory.signal.org%2F%22%2C%22https%3A%2F%2Fapi.backup.signal.org%2F%22%2C%22https%3A%2F%2Fcontentproxy.signal.org%2F%22%5D%7D&mv=1.2.0

**Comment by bassosimone** [comment]
@Te-k thank you for researching this bit of information! I've branched off #278 to implement a basic signal messenger experiment based on that.

**Comment by hellais** [comment]
@Te-k thanks for this! I believe Signal also has capability to do some amount of domain fronting.

Looking at the data inside of https://github.com/signalapp/Signal-Android/blob/0ef01cc620cc907da6078c93cc97d31e6612b3f3/app/src/main/java/org/thoughtcrime/securesms/push/SignalServiceNetworkAccess.java#L35, I see that there is a bunch of other addresses too which seem to be related to domain fronting.

It's probably useful to also figure out how that part of the app works too so we can check for it as well.

Let me cc some Signal developers again to see if they can help us measure where in the world their app is getting blocked with OONI Probe: @greyson-signal @alan-signal @moxie0 @jlund-signal @scottnonnenberg-signal @Imperiopolis-Signal @michaelkirk-signal.

**Comment by hellais** [comment]
The latest configuration of signal appears to be inside of the `SignalServiceNetworkAccess.java` file: https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/push/SignalServiceNetworkAccess.java#L222

The variables are in turn defined inside of the gradle build file: https://github.com/signalapp/Signal-Android/blob/master/app/build.gradle#L111

Maybe also the desktop app configs can be used: https://github.com/signalapp/Signal-Desktop/blob/development/config/production.json

**Comment by hellais** [comment]
We have now shipped this test as part of OONI Probe mobile and OONI Probe Desktop 🎉
