### ISSUE TITLE
spec: finalise orchestra docs

### ISSUE THREAD

**Issue by hellais** [ooni/probe-engine#258]
The OONI orchestration system is designed to instrument probes on what they should be doing in terms of what they should be testing, how and at which frequency.

During the berlin meeting we did quite a bit of brainstorming on what this should entail exactly and these notes can be found here: https://github.com/OpenObservatory/gatherings/blob/master/internal/2016-11-berlin/session-ooni-orchestration.md.

**Comment by hellais** [comment]
@FedericoCeratto mentioned about adding also documentation for every API endpoint that exists.

**Comment by bassosimone** [comment]
I am going to close this issue. We have a self-documenting mechanism for the API now that generates a Swagger. Our effort should be to improve this system and maintain it. There is no need to keep this issue open.
