### ISSUE TITLE
measurementkit: build in ordinary linux systems

### ISSUE THREAD

**Issue by ja-pa** [ooni/probe-engine#267]
Hi, I'm trying to create a package of probe-cli for OpenWrt. During compilation, probe-engine was failing on library linking  because of hardcoded path definition in https://github.com/ooni/probe-engine/blob/master/measurementkit/task_cgo.go
After adding these cgo definitions I was able to compile and run test probe-engine on OpenWrt.

```
@@ -38,6 +38,18 @@ import (
 	// #cgo linux,amd64 LDFLAGS: /usr/lib/libevent_extra.a
 	// #cgo linux,amd64 LDFLAGS: /usr/lib/libevent_pthreads.a
 	// #cgo linux,amd64 LDFLAGS: /lib/libz.a
+	//
+	// #cgo LDFLAGS: -lmeasurement_kit
+	// #cgo LDFLAGS: -lmaxminddb
+	// #cgo LDFLAGS: -lcurl
+	// #cgo LDFLAGS: -lnghttp2
+	// #cgo LDFLAGS: -levent_openssl
+	// #cgo LDFLAGS: -lssl
+	// #cgo LDFLAGS: -lcrypto
+	// #cgo LDFLAGS: -levent_core
+	// #cgo LDFLAGS: -levent_extra
+	// #cgo LDFLAGS: -levent_pthreads
+	// #cgo LDFLAGS: -lz
 	"C"
 	"errors"
 	"unsafe"
```
Is it possible to integrate similar changes to probe-engine master?

**Comment by bassosimone** [comment]
We would need to test whether this breaks out builds or not. The reasons paths for Linux are hard code is because we want to create a statically linked binary. I assume the build works for you if you export such LDFLAGS into an environment variable and run `go build`. Is that correct?

**Comment by ja-pa** [comment]
Thanks for the explanation. Yes, build works +- as you described. I'm thinking if it would be possible to solve this by some specific tag? But I don't know golang too much. . .

**Comment by bassosimone** [comment]
I will take a look

**Comment by bassosimone** [comment]
Should be fixed in https://github.com/ooni/probe-engine/pull/333 and https://github.com/ooni/probe-cli/pull/112. Awaiting confirmation from @ja-pa that it's WAI on OpenWrt.
