### ISSUE TITLE
Investigate ssl_error: error:00000000:lib(0):func(0):reason(0)

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#277]

**Comment by azadi** [comment]
An example of a measurement with this error:

https://explorer.ooni.org/measurement/20200116T122528Z_AS16135_Zwk2ENVXs6Qjd3qe7KuQ5co2DEGOcKfndljWpzDskMwc0a39zD?input=https%3A//ja.m.wikipedia.org/

**Comment by bassosimone** [comment]
I doubt we'll have time to investigate this. We'll probably switch to Go sooner.

**Comment by bassosimone** [comment]
We need to re-evaluate this, now that Web Connectivity is written in Go (https://github.com/ooni/probe-engine/pull/806).

**Comment by bassosimone** [comment]
Let us take another look at this issue in Sprint 21. It seems to me it's not straightforward how to provoke this error using Jafar when the measured application is `measurement_kit`. If we cannot understand the issue, then perhaps acknowledge that we cannot just work on this issue and therefore this will remain as a not fully understood bug of the past.

**Comment by bassosimone** [comment]
Effort is `1` and priority is `low` because we need to just check again if we can generate this with `jafar` or decide that there is nothing we can do about this issue in this limited time frame apart from making sure it's listed in https://github.com/ooni/probe-engine/issues/892.

**Comment by bassosimone** [comment]
After spending some time planning Sprint 21, I realised I don't have cycles to dedicate to this issue. I also have listed this issue in the list of issues that may have a data quality impact (tracking issue is https://github.com/ooni/probe-engine/issues/892, list of bugs has not been published yet, as I'm still vetting them, double checking, categorising). Thus, we are going to close this issue and consider that we will not fix the underlying bug. This seems reasonable, since now MK is legacy code we're dropping.
