### ISSUE TITLE
Basic signal messenger experiment

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#278]
This is about writing a basic reachability test for signal based off https://github.com/Te-k's comment here https://github.com/ooni/probe-engine/issues/244#issuecomment-575848902. This will hopefully be the first step towards a more comprehensive signal messenger experiment.

**Comment by hellais** [comment]
Use as blueprint the telegram test and look at RiseupVPN to see how to use a custom CA.

**Comment by bassosimone** [comment]
We did this!
