### ISSUE TITLE
Investigate using db-ip.com as a Maxmind replacement

### ISSUE THREAD

**Issue by hellais** [ooni/probe-engine#306]
This is related to: https://github.com/ooni/probe-engine/issues/269

**Comment by bassosimone** [comment]
This was actually done by @hellais. We concluded that we're doing the following:

1. replace MaxMind country DB with db-ip.com's country DB

2. keep using the MaxMind ASN DB for the time being

3. investigate a better solution regarding how to get ASN DB information

I will create follow-up issues and close this issue.

**Comment by bassosimone** [comment]
Follow-up issues:

* https://github.com/ooni/probe-engine/issues/336

* https://github.com/ooni/probe-engine/issues/334
