### ISSUE TITLE
Download the geoip database through HTTPS

### ISSUE THREAD

**Issue by tomac4t** [ooni/probe-engine#314]
If possible download the Maxmind database though HTTPS? It will be helpful for Chinese users, because `github.com` will trigger TCP RST packet in China. 
```bash
$ ./ooniprobe run im
2020/02/06 15:21:19 s.fetchResourcesIdempotent failed (error: Get http://github.com/ooni/probe-assets/releases/download/20191226162429/asn.mmdb.gz: read tcp 192.168.1.108:49550->13.250.177.223:80: read: connection reset by peer)
   ⨯ Failed to lookup the location of the probe error=Get http://github.com/ooni/probe-assets/releases/download/20191226162429/asn.mmdb.gz: read tcp 192.168.1.108:49550->13.250.177.223:80: read: connection reset by peer
   ⨯ failure in main command   error=Get http://github.com/ooni/probe-assets/releases/download/20191226162429/asn.mmdb.gz: read tcp 192.168.1.108:49550->13.250.177.223:80: read: connection reset by peer
```
Isn't get the releases URL though GitHub API? I didn't find that API in the code:-/

**Comment by hellais** [comment]
cc @bassosimone

**Comment by hellais** [comment]
Also note that we are likely going to soon change how this is being handled, because of the maxmind license changes (see: https://github.com/ooni/probe-engine/issues/269), but we will still keep using this old database for some time, so I still think we should change it to fetch it via HTTPS.

**Comment by bassosimone** [comment]
This is done. The fix will land when https://github.com/ooni/probe/issues/1010 will happen (soon).
