### ISSUE TITLE
probe-cli, miniooni: submit even when experiment failed

### ISSUE THREAD

**Issue by hellais** [ooni/probe-engine#316]
We got from a user report the following:
```
   49.17% psiphon experiment running
   • OnProgress: 1.000000 - psiphon experiment complete
   50.00% psiphon experiment complete
   • failure.measurement error=clientlib.StartTunnel#285: tunnel start produced error: clientlib.StartTunnel.func3#271: controller.Run exited unexpectedly
   • status.end
```

It looks like this should be handled properly, because currently it's generating an empty measurement file.

See:

```
[engine] jsonapi: request body: {}
[engine] jsonapi: method: POST
[engine] jsonapi: URL: https://ams-ps2.ooni.nu:443/report/XXXXXX/close
[engine] http: connection to 37.218.245.109:443 ready; sending request
[engine] > POST /report/XXXXXX/close HTTP/1.1
```

**Comment by bassosimone** [comment]
I can reproduce this bug by forcing a one-second timeout of the experiment. Log excerpt:

```
[      2.012007] <warn> measurement failed: map[error:clientlib.StartTunnel#285: tunnel start produced error: clientlib.StartTunnel.func3#271: controller.Run exited unexpectedly]
[      2.012081] <debug> jsonapi: request body: {}
[      2.012104] <debug> jsonapi: method: POST
```

No file is also written on disk by `miniooni`. 🤔

**Comment by bassosimone** [comment]
This is not an issue of `probe-engine`. It is an issue of `miniooni` and `probe-cli` that should continue also if the experiment function returns an `err`. I'll push soon my fix for `miniooni` and will apply the same change also to `probe-cli`.

**Comment by bassosimone** [comment]
Here's the fix for miniooni: https://github.com/ooni/probe-engine/pull/324/commits/13cb84ef3ca3c5d78adbefc4ee695b51683f1efc

Something similar is required for probe-cli.
