### ISSUE TITLE
Add failover to probes

### ISSUE THREAD

**Issue by hellais** [ooni/probe-engine#407]
We could potentially open many connections to collectors and just keep the faster one.

Possibly related to: https://github.com/ooni/backend/issues/366.

**Comment by bassosimone** [comment]
This is rather difficult to do until we have the guarantee that we always use the probe services and until we refactor the code to reflect that, removing passing from the bouncer for collectors.

I did https://github.com/ooni/probe-engine/issues/19 instead, which has the same effort estimate.

**Comment by bassosimone** [comment]
To do this, we need to do https://github.com/ooni/probe-engine/issues/621 first. Once that is done, we can modify `session.go·queryBouncer` to attempt fetching TestHelpers from every possible `https` probe service. The fastest probe service would then be chosen. If no `https` probe service is working, we could then fallback to `cloudfronted` bouncers. The choice of the probe service will be saved, and reused for later when open the report, etc.

**Comment by bassosimone** [comment]
Discussed today with @FedericoCeratto and @hellais: we will create N entries like `https://ps$N.ooni.io` (or something similar) and the code will try these entries first. It will choose the one that is fastest to fetch the test helpers. If none of them work, we do fallback like we do now. This strikes a balance between reliability and selecting the most performance probe services endpoint.

**Comment by bassosimone** [comment]
(Swapped efforts with https://github.com/ooni/probe-engine/issues/621)

**Comment by bassosimone** [comment]
Has been implemented. We're still missing DNS names for every data centre. Will discuss this tomorrow in our backend meeting so we're sure we will create follow-up issues.
