### ISSUE TITLE
Migrate ndt7 to location services v2

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#562]
Quite urgent, since there is someone hammering m-lab with ndt7 tests in a loop.

**Comment by stephen-soltesz** [comment]
@bassosimone in staging the v2beta1  path is accessible from the default App Engine URL. https://mlab-staging.appspot.com/v2beta1/query/ndt/ndt7

Early next week, I expect us to deploy this to production, which should make the canonical locate URL include the v2beta1 path also.

https://locate.measurementlab.net/v2beta1/query/ndt/ndt7 (will work early next week)

**Comment by stephen-soltesz** [comment]
Also, FYI: the mlab3 machines currently being targeted by ndt7-client.exe have been shutdown temporarily in an attempt to make contact with the client distribution maintainer.

**Comment by bassosimone** [comment]
ACK, thanks for keeping me posted!

**Comment by stephen-soltesz** [comment]
@bassosimone https://locate.measurementlab.net/v2beta1/query/ndt/ndt7 is available now.

**Comment by stephen-soltesz** [comment]
Be advised - there is a bug at the moment that will cause all access tokens to be rejected. This is caused by a mismatch between the actual and expected node name. I'm working on a fix. This need not block other work preparing to use the v2 api.

**Comment by bassosimone** [comment]
Thanks! (I will most likely work on it next week!)

**Comment by stephen-soltesz** [comment]
Okay -- access tokens work correctly now: https://locate.measurementlab.net/v2beta1/query/ndt/ndt7

**Comment by bassosimone** [comment]
To perform this task we need to create a new package `internal/mlablocate2` which is a fork of the original `internal/mlablocate` where we parse the response differently. A possibly annoying issue is that we won't have the site name in the response anymore. We can hopefully extract it with a regex, even though I am wondering that the upcoming m-lab naming change will cause us issues.

**Comment by stephen-soltesz** [comment]
The m-lab naming change should be invisible from the locate/v2 API. The locate/v2 API only returns "siteinfo/v2" hostnames.

You may easily parse the machine name to extract the site using https://godoc.org/github.com/m-lab/go/host#Parse

**Comment by bassosimone** [comment]
@stephen-soltesz that is very useful to know. I believe I can import/vendor that code and solve the same problem in another way. Thanks for letting me know.
