### ISSUE TITLE
Strip private bridge addresses

### ISSUE THREAD

**Issue by hellais** [ooni/probe-engine#643]
From slack @bassosimone said:

> it's tricky: the only thing that works reliably is to serialise a JSON and then unconditionally strip everything that looks like an IP address
> I would like to spend some time thinking at whether there is a better way and whether such way is robust or not

**Comment by bassosimone** [comment]
We need to modify [this code as follows](https://github.com/ooni/probe-engine/blob/9ead0e178a8b6d17bff0ebf9654626b3cbe14163/experiment/tor/tor.go#L253):

```diff
-	rc.mu.Lock()
	tr := TargetResults{
		Agent:          "redirect",
		Failure:        setFailure(err),
		NetworkEvents:  oonidatamodel.NewNetworkEventsList(tk),
		Queries:        oonidatamodel.NewDNSQueriesList(tk),
		Requests:       oonidatamodel.NewRequestList(tk),
		TargetAddress:  kt.target.Address,
		TargetName:     kt.target.Name,
		TargetProtocol: kt.target.Protocol,
		TCPConnect:     oonidatamodel.NewTCPConnectList(tk),
		TLSHandshakes:  oonidatamodel.NewTLSHandshakesList(tk),
	}
	tr.fillSummary()
+	tr = sanitise(tr, kt.target.Source == "bridgedb")
+	rc.mu.Lock()
	rc.targetresults[kt.key] = tr
	rc.mu.Unlock()
	sofar := rc.completed.Add(1)
	percentage := 0.0
	if total > 0 {
		percentage = float64(sofar) / float64(total)
	}
	rc.callbacks.OnProgress(percentage, fmt.Sprintf(
-		"tor: access %s/%s: %s", kt.target.Address, kt.target.Protocol,
+		"tor: access %s/%s: %s", kt.target.maybeAddress(), kt.target.Protocol,
		errString(err),
	))
```

**Comment by bassosimone** [comment]
We have implemented the functionality at https://github.com/ooni/probe-engine/pull/720.

We have updated the specification at https://github.com/ooni/spec/pull/195.

We have documented additional next steps at https://github.com/ooni/probe-engine/issues/721.

We are done.
