### ISSUE TITLE
ios: remove MK 

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#668]
- [x] write equivalent of classes we added to Android
- [x] remove hack to avoid `@import` in `build-ios.bash`
- [x] rename `.mm` files in ooni/probe-ios
- [x] remove unused and deprecated classes in the `Engine`

**Comment by lorenzoPrimi** [comment]
@bassosimone we should separate what's iOS to Android here

**Comment by bassosimone** [comment]
@lorenzoPrimi that's a good observation! Please, feel encouraged to start doing this work! Thanks for pointing this out!

**Comment by bassosimone** [comment]
@lorenzoPrimi so, it seems this issue now only contains iOS related work (it seems we already did all the Android work and we also have issue https://github.com/ooni/probe-engine/issues/590 covering probe-engine related work). I'm going to rename it accordingly. I think this addresses your previous concern because it means we don't need to separate what is iOS and what is Android.

**Comment by bassosimone** [comment]
We have changed the scope of this issue to encompass the act of porting the iOS app to the post-MK world. This was discussed with @lorenzoPrimi last week. As a result, I have also adapted the check list and added this note.

**Comment by bassosimone** [comment]
This is now complete! Closing!
