### ISSUE TITLE
session.go: create random directory within TempDir

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#671]
The `TempDir` provided by the user shall be the base directory. We need to create another directory, whose name must contain some randomness, inside such `TempDir`.

**Comment by lorenzoPrimi** [comment]
on iOS we can use something like 
`
self.temp_dir = [NSTemporaryDirectory() stringByAppendingPathComponent:[NSString stringWithFormat:@"%f", [[NSDate date] timeIntervalSince1970]]];
`

I wonder if we need to clean that directory at the end of the test as according to the documentation, the tmp folder could be deleted any time, if the app is not executing:

> The system may also purge lingering files from this directory when your app is not running.

Also the documentation states:

> Your app should remove files from this directory when it determines they are no longer needed.

The emphasis here being on the app developer to do their own housekeeping and not leave it for the OS to tidy up after them.

**Comment by lorenzoPrimi** [comment]
For the same reason I assume on Android we should use `getFilesDir` for the assets, instead of `getCacheDir` and clean up the files when they are not needed, not giving power to the user to delete some important files that will be re-downloaded on the first run

**Comment by bassosimone** [comment]
So, we further discussed this issue with @lorenzoPrimi and concluded the following.

1. apps use as temporary dir `$TMPDIR/ooniprobe`

2. engine modifies that to `$TMPDIR/ooniprobe/ooni.XXXXX`

3. engine removes `ooni.XXXXX` on `session.Close`

4. we don't want assets on the cache dir
