### ISSUE TITLE
obfs4proxy reachability in probe-engine

### ISSUE THREAD

**Issue by hellais** [ooni/probe-engine#90]

**Comment by NullHypothesis** [comment]
For what it's worth, I've been working on a golang service, [bridgestrap](https://dip.torproject.org/phw/bridgestrap), which takes as input a bridge line, and tells you if it could bootstrap a Tor circuit over the given bridge. I'm mentioning this because it may be useful as part of this issue.

**Comment by bassosimone** [comment]
This has been superseded by #226. We will close as wontfix as discussed in #226.
