### ISSUE TITLE
Read from file error: New line difference in Unix(LF) and Windows(CRLF)

### ISSUE THREAD

**Issue by xhdix** [ooni/probe-engine#980]
**To Reproduce**
Create a text file in Windows and use it in Linux!

```
[     10.806731] <info> [24/32] running with input: https://dns.google/dns-query
[     10.806815] <warn> measurement failed: map[error:the input URL is invalid: parse "https://dns.google/dns-query\r": net/url: invalid control character in URL]
[     10.806826] <info> submitting measurement to OONI collector; please be patient...
[     10.806856] <debug> httpx: request body: 920 bytes
[     10.806863] <debug> httpx: method: POST
[     10.806869] <debug> httpx: URL: https://ps2.ooni.io/report/20201013T132548Z_AS58224_CMHxqiDagokNTdbDPAF9Svp7cXSSHxvtKJEixKXhDtvS6DJFLi
```

**Comment by bassosimone** [comment]
We have done some progress on this issue in Sprint 24. We now have a skeleton of a very good pull request that solves the problem and we are discussing how to finish structuring tests so all the code is tested. Should really land in Sprint 25.

Thanks @xhdix for all the hard and great work done so far! Apologies for the delays in the review. I have been very much focused on helping with the infrastructure migration and could hardly do much more.

**Comment by bassosimone** [comment]
Fixed by https://github.com/ooni/probe-engine/pull/1013
