### ISSUE TITLE
telegram: update IP addresses used by the experiment

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#999]
See https://github.com/ooni/probe-legacy/pull/74

**Comment by bassosimone** [comment]
Potentially useful resource: https://www.qurium.org/alerts/telegram-latency-and-belarus/

**Comment by pes2020kk** [comment]
👍

**Comment by hellais** [comment]
A PR for this is ready for review: https://github.com/ooni/probe-cli/pull/232. It turns out they only added one additional endpoint and the other ones we had in the configuration are still live.

**Comment by bassosimone** [comment]
done!
